apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "APPDEV_INTRANET.fullname" . }}
  labels:
    {{- include "APPDEV_INTRANET.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "APPDEV_INTRANET.fullname" . }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
          podSelector:
            matchLabels:
              app.kubernetes.io/component: controller